version: "3.7"

services:
  verdaccio:
    container_name: verdaccio
    image: verdaccio/verdaccio
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - 4873:4873
    expose:
      - 4873
    volumes:
      - './home/verdaccio/config:/verdaccio/conf'

  db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: windmill
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  windmill_server:
    # Use ghcr.io/windmill-labs/windmill-ee:main for the ee
    image: ghcr.io/windmill-labs/windmill:main
    pull_policy: always
    deploy:
      replicas: 1
    restart: unless-stopped
    expose:
      - 8000
    environment:
      - DATABASE_URL=postgres://postgres:${DB_PASSWORD}@db/windmill?sslmode=disable
      - BASE_URL=${WM_BASE_URL}
      - RUST_LOG=info
      ## You can set the number of workers to > 0 and not need any separate worker service but not recommended
      - NUM_WORKERS=0
      - DISABLE_SERVER=false
      - METRICS_ADDR=false
      - NPM_CONFIG_REGISTRY=http://verdaccio:4873
    depends_on:
      db:
        condition: service_healthy

  windmill_worker:
    # Use ghcr.io/windmill-labs/windmill-ee:main for the ee
    image: ghcr.io/windmill-labs/windmill:main
    pull_policy: always
    deploy:
      replicas: 1
    restart: unless-stopped
    environment:
      - NPM_CONFIG_REGISTRY=http://verdaccio:4873
      - DATABASE_URL=postgres://postgres:${DB_PASSWORD}@db/windmill?sslmode=disable
      - BASE_URL=${WM_BASE_URL}
      - RUST_LOG=info
      - NUM_WORKERS=1
      - DISABLE_SERVER=true
      - KEEP_JOB_DIR=false
      - METRICS_ADDR=false
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - worker_dependency_cache:/tmp/windmill/cache

  lsp:
    image: ghcr.io/windmill-labs/windmill-lsp:latest
    restart: unless-stopped
    expose:
      - 3001

  caddy:
    image: caddy:2.5.2-alpine
    restart: unless-stopped

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - 80:80
    environment:
      - BASE_URL=":80"

volumes:
  db_data: null
  worker_dependency_cache: null
